[color]
bg           = #FDF0ED
fg           = #1a1c23
black        = #1A1C23
black-alt    = #757575
red          = #EC6A88
red-alt      = #e95678
green        = #3FDAA4
green-alt    = #29d398
yellow       = #FBC3A7
yellow-alt   = #fab795
blue         = #3FC6DE
blue-alt     = #26bbd9
magenta      = #F075B7
magenta-alt  = #ee64ae
cyan         = #6BE6E6
cyan-alt     = #59e3e3
white        = #e5e5e5
white-alt    = #e5e5e5

