[color]
bg           = #FDF0ED
fg           = #1a1c23
black        = #FDF0ED
black-alt    = #1c1e26
red          = #E84A72
red-alt      = #e95678
green        = #29d398
green-alt    = #29d398
yellow       = #fab795
yellow-alt   = #fab795
blue         = #3FC6DE
blue-alt     = #26bbd9
magenta      = #F075B7
magenta-alt  = #ee64ae
cyan         = #6BE6E6
cyan-alt     = #59e3e3
white        = #e5e5e5
white-alt    = #e5e5e5

