[color]

bg           = #fbf1c7
fg           = #3c3836

black        = #ebdbb2
black-alt    = #7c6f64

red          = #cc241d
red-alt      = #9d0006

green        = #98971a
green-alt    = #79740e

yellow       = #d79921
yellow-alt   = #b57614

blue         = #458588
blue-alt     = #076678

magenta      = #b16286
magenta-alt  = #8f3f71

cyan         = #689d6a
cyan-alt     = #427b58

white        = #7c6f64
white-alt    = #282828
