[colors]
# Special Colors
background=282828
foreground=ebdbb2
cursor=282828 ebdbb2
regular0=7c6764  # black
regular1=ea6962  # red
regular2=a9b665  # green
regular3=e78a4e  # yellow
regular4=7daea3  # blue
regular5=d3869b  # magenta
regular6=89b482  # cyan
regular7=d4be98  # white
bright0=7c6764   # bright black
bright1=ea6962   # bright red
bright2=a9b665   # bright green
bright3=e78a4e   # bright yellow
bright4=7daea3   # bright blue
bright5=d3869b   # bright magenta
bright6=89b482   # bright cyan
bright7=d4be98   # bright white
flash=404040
