[color]

bg           = #282828
fg           = #ebdbb2

black        = #7c6764
black-alt    = #7c6764

red          = #ea6962
red-alt      = #ea6962

green        = #a9b665
green-alt    = #a9b665

yellow       = #e78a4e
yellow-alt   = #e78a4e

blue         = #7daea3
blue-alt     = #7daea3

magenta      = #d3869b
magenta-alt  = #d3869b

cyan         = #89b482
cyan-alt     = #89b482

white        = #d4be98
white-alt    = #d4be98

