[color]

fg =          #1f2328
bg =          #ffffff

black =       #24292f
black-alt =   #57606a

red =         #C05589
red-alt =     #D9006A

green =       #B26A3E
green-alt =   #744527

yellow =      #E89867
yellow-alt =  #FF6400

blue =        #429484
blue-alt =    #00AF8D

magenta =     #933362
magenta-alt = #A8195F

cyan =        #A9D65F
cyan-alt =    #93EE00

white =       #FFF5EF
white-alt =   #FFFFFF

