[color]

fg          =    #ffffff
bg          =    #1f2328

black       =    #24292f
black-alt   =    #777777

red         =    #EFAFD1
red-alt     =    #DB8DB3
green       =    #D2F9D6
green-alt   =    #ACE5B3
yellow      =    #F4BCAE
yellow-alt  =    #F4A792
blue        =    #AFEFEA
blue-alt    =    #85DDD9
magenta     =    #C6C5FC
magenta-alt =    #9E96ED
cyan        =    #75E0D5
cyan-alt    =    #48C1B8


white       =    #FFF5EF
white-alt   =    #FFFFFF

