general {
    col.active_border = rgba(1f2328aa)
    col.inactive_border = rgba(ffffffaa)
}

misc {
    background_color = rgba(232323ee)
}

decoration {
    shadow {
        color = rgba(1a1a1aee)
    }
}

