[color]

fg =          #1f2328
bg =          #ffffff

black =       #24292f
black-alt =   #57606a

red =         #cf222e
red-alt =     #a40e26

green =       #116329
green-alt =   #1a7f37

yellow =      #4d2d00
yellow-alt =  #633c01

blue =        #0969da
blue-alt =    #218bff

magenta =     #8250df
magenta-alt = #a475f9

cyan =        #1b7c83
cyan-alt =    #3192aa

white =       #6e7781
white-alt =   #8c959f
