[color]
bg           = #1c1e26
fg           = #d5d8da
black        = #1c1e26
black-alt    = #848484
red          = #e95678
red-alt      = #ec6a88
green        = #29d398
green-alt    = #3fdaa4
yellow       = #fab795
yellow-alt   = #fbc3a7
blue         = #26bbd9
blue-alt     = #3fc4de
magenta      = #ee64ae
magenta-alt  = #f075b5
cyan         = #59e3e3
cyan-alt     = #6be4e6
white        = #e5e5e5
white-alt    = #e5e5e5

