#!/bin/sh

#               1   2   3   4   5   6   7   8   9   0   BkSp
bspc monitor -d web trm trm trm dmo bug lac com cal gvc pers

setxkbmap gb
xsetroot -cursor_name left_ptr
xrdb -load ~/.Xresources

sxhkd &

bspc config border_width          2
bspc config top_padding           0
bspc config window_gap            5
bspc config split_ratio           0.619
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config automatic_scheme      longest_side
bspc config pointer_modifier      mod1
bspc config pointer_action1       move
bspc config pointer_action2       resize_corner

bspc rule -a *:*:"meet.google.com is sharing your screen." hidden=on
bspc rule -a *:*:"teams.microsoft.com is sharing your screen." hidden=on
bspc rule -a *:*:"zoom.us is sharing your screen." hidden=on

sh "${HOME}/.themes/default/bspwm.theme"

