#! /bin/sh

bspc monitor  -d web dev eml trm trm trm trm trm trm
#bspc monitor LVDS-1 -d web dev eml trm trm trm trm trm trm
#bspc monitor VGA-1 -d web dev eml trm trm trm trm trm trm

bspc config border_width         	2
bspc config window_gap           	10
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true

bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
