[color]

bg           = #3c3836
fg           = #ebdbb2

black        = #282828
black-alt    = #928374

red          = #cc241d
red-alt      = #fb4934

green        = #98971a
green-alt    = #b8bb26

yellow       = #d79921
yellow-alt   = #fabd2f

blue         = #458588
blue-alt     = #83a598

magenta      = #b16286
magenta-alt  = #d3869b

cyan         = #689d6a
cyan-alt     = #8ec07c

white        = #a89984
white-alt    = #ebdbb2

