[color]

fg =          #c8d3f5
bg =          #222436

black =       #1b1d2b
black-alt =   #444a73

red =         #ff757f
red-alt =     #ff757f

green =       #c3e88d
green-alt =   #c3e88d

yellow =      #ffc777
yellow-alt =  #ffc777

blue =        #82aaff
blue-alt =    #82aaff

magenta =     #c099ff
magenta-alt = #c099ff

cyan =        #86e1fc
cyan-alt =    #86e1fc

white =       #828bb8
white-alt =   #c8d3f5
